language: ruby

rvm:
- 2.3.3

sudo: false

before_script:
 - chmod +x ./ci-build.sh

script: ./ci-build.sh

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: azure_web_apps
  on: master
  username: tintoy-blog\tintoy-blog
  password:
    secure: "hFY+U010UYa/7tKSVUd1AizPNPtCiFwph1Cg2vH7wEpopbHPu7wnwxhWlpX0SuAdvc42ivZ+z/+KDflk5P74Q+GE9qqq9UGQAB5WfiRh3SPFQyQ3j5/4IbRqZwEExt72E8ALWfyK/kQHmw5XcQGxXk7lJ6Ll9hs0Vt2qKRh6FfezvIUQ4GMXrqlCRg7s+yaHQ1hZdP3Tl0Qyl1BsrLFtlE8Hyrb/f9UxkWQ/6oij68JpHF0qcLWFZ0gwSpzhK+uHLtWkVKjwIx7CGdOMlljHXbrF/dBFF9hCypczbLYDYP948Oqs6M9s/fRkdQP8FC/e91h8sfp3haB1eu3LfxkhscxswOlnRoUOQDcwXneGk1n/g3FXb8cLX8x4D0KyZC2kXDnmvQCTSRAWuGu2CWSaO4uhin3Nr/FjOe/ByaG1zXlkGlQKTRxG4YMAT+o89l3wcFaksZOZF73uzF/Ai47F2kNhU/xRnWfFFfMQlLSdyb9sjRILGEWMG58rqBI2SKaW2ThpPO3eQTOSMx4OBPJS98UgIzm1+cbSTVMlkDIVHMB/6mpAyzqoJvjOF8FM20wLxr8uzGyjDbOVKnG+9IGoctZwhh8Iz3y+VRmwdLclFLRrKDz37Qfa12sTDY86N/Zah4qC8MVOPUDERN7I2LSWiPdJk8LWLVTmYtDbpl0BB3A="
  site: tintoy-blog
