language: ruby

rvm:
- 2.3.3

sudo: false

before_script:
 - chmod +x ./ci-build.sh

script: ./ci-build.sh

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
