# Site settings
title: tin oscillator
description: >
  Software development is about sharing ideas; bridging the innner and outer worlds.
baseurl: ""
url: "http://blog.tintoy.io"
# url: "http://localhost:3000" # for local dev

# User settings
username: tintoy
user_title: Adam Friedman
email: blog@tintoy.io
twitter_username: TinOscillator
github_username:  tintoy
disqus_username: tintoy-blog

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/
gems:
  - jekyll-gist
  - jekyll-compose

# HTML minification
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in nav menu
links:
  - title: home
    shortcut: h
    url: /
  - title: posts
    shortcut: p
    url: /posts
  - title: posts by series
    shortcut: =
    url: /series
  - title: tags
    shortcut: t
    url: /tags
  - title: about
    shortcut: a
    url: /about

# Recent projects
projects:
  - name: terraform-provider-ddcloud
    url: https://github.com/DimensionDataResearch/dd-cloud-compute-terraform
  - name: docker-machine-driver-ddcloud
    url: https://github.com/DimensionDataResearch/docker-machine-driver-ddcloud
  - name: Docker.DotNet.Reactive
    url: https://github.com/tintoy/Docker.DotNet.Reactive
  - name: HTTPlease
    url: https://github.com/tintoy/HTTPlease
  - name: seqlog
    url: https://github.com/tintoy/seqlog
  - name: rx-akkadotnet
    url: https://github.com/tintoy/rx-akkadotnet

# Exclude NodeJS stuff
exclude: ['package.json', 'src', 'gulpfile.js', 'node_modules', 'LICENSE', 'vendor']
